services:
    backend:
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - mongo
        networks:
            - my-network

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - my-network

networks:
    my-network:

